// Generated by CoffeeScript 1.11.1
var apiInstance, app, express, restify;

express = require('express');

restify = require('./app.js');

app = express();

apiInstance = new restify('./config.json');

apiInstance.onload(function(status, context) {
  return app.use('/', context.as_view());
});

app.listen(3000, function() {
  return console.log('Example app listening on port 3000!');
});
