// Generated by CoffeeScript 1.11.1
var apiInstance, app, chalk, express, parser, restify;

express = require('express');

restify = require('./app.js');

parser = require('body-parser');

chalk = require('chalk');

app = express();

app.use(parser.urlencoded({
  extended: false
}));

apiInstance = new restify;

apiInstance.loadJson('./config.json');

apiInstance.onload(function(status, context) {
  return app.use('/', context.as_view());
});

app.listen(3000, function() {
  return console.log(chalk.red('App listening on port 3000!'));
});
