// Generated by CoffeeScript 1.11.1
var bcrypt, jwt, routes, utils;

bcrypt = require('bcrypt');

jwt = require('jsonwebtoken');

routes = function(route, model, router) {
  router.get(route, function(req, res, next) {
    return res.send("this is the auth endpoint");
  });
  router.post(route, function(req, res, next) {
    var password, username;
    username = req.body['username'];
    password = req.body['password'];
    return model.findOne({
      username: username
    }, function(err, model) {
      var hash;
      if (err) {
        res.status(401).end();
      }
      hash = model.password;
      return bcrypt.compare(req.body['password'], hash, function(err, match) {
        var token;
        if (err) {
          return res.status(401).end();
        }
        if (match) {
          token = jwt.sign({
            user: model,
            salt: Math.random()
          }, 'shhhhh');
          return res.status(200).json({
            key: token
          });
        } else {
          return res.status(401).end();
        }
      });
    });
  });
  router["delete"](router, function(req, res, next) {
    return res.send("You successfully logged out of the application");
  });
  return router.post(route + "/signup", function(req, res, next) {
    req.body['is_superuser'] = false;
    req.body['token'] = "";
    return bcrypt.hash(req.body['password'], 5, function(err, password) {
      if (err) {
        return res.status(401).end();
      }
      req.body.password = password;
      return new model(req.body).save(function(err) {
        if (err) {
          return res.status(401).json(err);
        }
        return res.send("route to create new user");
      });
    });
  });
};

utils = function() {
  var is_authenticated, is_superuser;
  is_authenticated = function() {
    return console.log("Test if the user is authenticated");
  };
  return is_superuser = function() {
    return console.log("test if is_superuser");
  };
};

module.exports["utils"] = utils;

module.exports["routes"] = routes;
